apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - HTTP-route.yaml
  - github-secret.yaml
  - service.yaml
  - auth-secret.yaml
images:
  - name: ghcr.io/simonbrundin/software-agent
    newTag: "frontend-1.6.4"
